spring:
  # 相关的配置
  shardingsphere:
    props:
      sql-show: true
    datasource:
      common:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
      names: master,salve0
      # 主库
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://127.0.0.1:3336/db?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=true&characterEncoding=utf-8
        username: root
        password:
      # 从库
      salve0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://127.0.0.1:3337/db?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=true&characterEncoding=utf-8
        username: root
        password:
        # 配置读写分离
        # 配置从库选择策略，提供轮询与随机，这里选择用轮询
    rules:
      replica-query:
        data-sources:
          ds:
            primary-data-source-name: master
            replica-data-source-names: salve0
            load-balancer-name: round-robin
        load-balancers:
          round-robin:
            type: ROUND_ROBIN
            props:
              defaule: 0
#    main:               #设置bean允许被覆盖
#        allow-bean-definition-overriding: true
    mybatis:
      mapper-locations: classpath:mapper/*.xml