server:
  port: 8088

spring:
  application:
    name: redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 5000 # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-idle: 15
        max-active: 15
        max-wait: 1000
